#+title: LS4GAN's Toy Zero

Bare first steps toward LS4GAN.  *still work in progress*

* Overview

We pick our two domains to consist of LAr TPC detector simulation with
a quasi 1D and a 2D model for the field response.  The 1D is formed by
simply zeroing out all off-center contributions to long-range
induction effects.  Withing the 0-wire region, the responses curves in
the usual 10 fine bins are kept (thus the "quasi" qualifier).

For eventual training of LS4GAN we identify data samples from the "1D"
model as "fake" and those from the "2D" model as "real".

* Prepare

** Wire-Cell Toolkit

WCT libraries and the ~wire-cell~ command are required.  See
https://wirecell.bnl.gov/ for an entry point.

Check that this works:

#+begin_example
  $ wire-cell --help
#+end_example

** Wire-Cell and other Python

The stand-alone ~wire-cell-python~ package, the ~snakemake~ program and
various other Python 3 packages are required.  It is recommended to
install them into a Python virtual environment created in whatever way
you prefer.  One simple way is:

#+begin_example
  $ python3 -m venv venv
  $ source venv/bin/activate
#+end_example

Once in the active Python virtual environment install the packages:

#+begin_example
  $ pip install -r requirements.txt
#+end_example

This will install Wire-Cell's Python package, snakemake, ipython and
some other needed goodies.  Sanity test: 

#+begin_example
  $ wirecell-<TAB>
  $ wirecell-util --help
  $ snakemake --help
#+end_example


* Run toy

Exercising the toy zero involves downloading various files and running
various programs.  The work is automated through Snakemake.  All may
be done at top level by running:

#+begin_export 
  $ snakemake -jall all
  $ tree data plots
#+end_export

If you look into the [[file:Snakefile][Snakefile]] you will find the automation is
factored into these parts:

- resp :: get 2D WCT "response file" and derive from it quasi-1D
  response file and make some diagnostic plots for each..

- wires :: get WCT "wires file" and make a diagnostic plot.

- depos :: generate sets of ionization point depositions for input to
  the WCT simulation.

- wct :: run ~wire-cell~ 
